### PR TITLE
Add rifts closed to hiscores

### PR DESCRIPTION
**Pull request by TastyPumPum**
Adds the guardians of the rift to the hiscores

-   [x] I have tested all my changes thoroughly.

### CODE REVIEW

**Comment by masonfox** [comment]
This is relevant to my issue #293

**Comment by masonfox** [comment]
@TastyPumPum, any insight as to when this will be merged? Affecting my Discord bot.

**Comment by TastyPumPum** [comment]
No idea hopefully @gc looks at it soon, but I can't give any time indication

**Comment by masonfox** [comment]
@gc, when will the new NPM version be released? It looks as though it is 2 months stale and I am still experiencing this #293 as a result of this PR not being published.

**Comment by gc** [comment]
@masonfox its published now

**Pull request merged**
